<a href="https://colab.research.google.com/github/redrabbit329/colab_pypydl/blob/master/Ch7_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ch7. NumPy
## 7.1. NumPy 개요
### 7.1.1. NumPy가 하는 일
   - NumPy : 파이썬으로 벡터, 행렬계산을 빠르게 하도록 특화된 기본 라이브러리(파이썬코드묶음)
   - 자주 사용되는 라이브러리 : SciPy, Pandas, scikit-learn, Matplotlib etc,.
### 7.1.2. NumPy의 고속 처리 경험하기

In [0]:
# 7-1
# 필요한 라이브러리를 import합니다.
import numpy as np
import time
from numpy.random import rand

# 행, 열의 크기
N = 150

# 행렬을 초기화합니다
matA = np.array(rand(N,N))
matB = np.array(rand(N,N))
matC = np.array([[0] * N for _ in range(N)])

# 파이썬의 리스트를 사용하여 계산합니다.
# 시작 시간을 저장합니다.
start = time.time()

# for문을 사용하여 행렬 곱셈을 실행합니다.
for i in range(N):
  for j in range(N):
    for k in range(N):
      matC[i][j] = matA[i][k] * matB[k][j]

print("파이썬 기능만으로 계산한 결과: %.2f[sec]" % float(time.time() - start))

# NumPy를 사용하여 계산합니다.
# 시작 시간을 저장합니다.
start = time.time()

# NumPy를 사용하여 행렬 곱셈을 실행합니다.
matC = np.dot(matA, matB)

# 소수점 이하 두 자리까지 표시되므로, NumPy는 0.00[sec]으로 표시됩니다.
print("NumPy를 사용하여 계산한 결과: %.2f[sec]" % float(time.time() - start))

파이썬 기능만으로 계산한 결과: 3.76[sec]
NumPy를 사용하여 계산한 결과: 0.00[sec]


## 7.2. NumPy 1차원 배열
### 7.2.1. import
   - import numpy로 임포용 (import numpy as np)
   - numpy.모듈명 형태로 사용 (np.모듈명)

### 7.2.2. 1차원 배열
   - NumPy 라이브러리 안에는 배열을 고속으로 처리하는 ndarray클래스가 준비되어 있음
   - np.array(리스트) 로 리스트를 전달하여 ndarray를 생성할 수 있음 : np.arry([1,2,3])
   - np.arange() 함수를 이용할수도 있음 : np.arange(X) 로 표ㅣ하여 일정한 간격으로 증감시킨 값의 요소를 X개 만들어줌 : np.arange(4)
   - ndarray 클래스는 1차원을 벡터, 2차원을 행렬, 3차원 이상을 텐서 라고 함

In [0]:
# 7-3
import numpy as np
print(np.array([1,2,3]))
print(np.arange(4))     # 요소 수 4개, 0부터 시작
array_1d = np.array([1,2,3,4,5,6,7,8])        # 1차원 ndarray 클래스
array_2d = np.array([[1,2,3,4],[5,6,7,8]])    # 2차원 ndarray 클래스
array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


[1 2 3]
[0 1 2 3]


In [0]:
# 7-5
import numpy as np

storages = [24,3,4,23,10,12]
print(storages)

np_storages = np.array(storages)
print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


### 7.2.3. 1차원 배열의 계산
   - 리스트에서는 요소별로 계산하기 위해 루프시킨 뒤 하나씩 더했지만, ndarray에서는 루프를 사용하지 않아도 된다. ndarray의 산술 연산은 같은 위치에 있는 요소끼리 계산된다.

In [0]:
# 7-7 1차원 배열 계산의 예
# NumPy를 사용하지 않고 실행
storages = [1,2,3,4]
new_storages =[]
for n in storages:
  n += n
  new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [0]:
# 7-8 : 1차원 배열 계산의 예 
# NumPy를 사용하여 실행함
import numpy as np
storages = np.array([1,2,3,4])
storages += storages
print(storages)

[2 4 6 8]


In [0]:
# 7-9
import numpy as np

arr = np.array([2,5,3,4,8])
# arr + arr
print(arr+arr)
print(arr-arr)
print(arr**3)
print(1/arr)

[ 4 10  6  8 16]
[0 0 0 0 0]
[  8 125  27  64 512]
[0.5        0.2        0.33333333 0.25       0.125     ]


In [0]:
# 7.2.4. 인덱스 참조와 슬라이스
# 7-11 : 슬라이스의 예
import numpy as np
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [0]:
import numpy as np 
arr = np.arange(10)
arr[0:3] = 1
print(arr)

[1 1 1 3 4 5 6 7 8 9]


In [0]:
# 7-13
import numpy as np
arr = np.arange(10)
print(arr)
# print 3,4,5 (3:6)
print(arr[3:6])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]


In [0]:
# 7.2.5. ndarray사용 시 주의 사항
# 파이썬의 리스트와 동일하게, nparray 배열을 다른 변수에 그대로 대입한 경우, 해당 변수의 값을 변경하면, 원래 ndarray배열의 값도 변경된다.
# 복사할 배열.copy() 메서드를 사용하여 복사하여 사용하여야 ndarray배열을 복사하여 독립적인 변수로 사용이 가능하다.
# ndarray를 그대로 arr1변수에 대입한 경우를 살펴본다.
import numpy as np

arr1 = np.array([1,2,3,4,5])
print("arr1 :", arr1)
arr2 = arr1
arr2[0] = 100
print(arr1)

arr1 : [1 2 3 4 5]
[100   2   3   4   5]


In [0]:
# 7-15 : ndarray를 copy()를 사용하여 arr2에 대입한 경우를 살펴 본다.
import numpy as np
arr1 = np.array([1,2,3,4,5])
print("arr1 :",arr1)
arr2 = arr1.copy()
arr2[0] = 100
print("arr2 :",arr2)
print("arr1 :",arr1,"copy()메서드로 복사하면, 변경이 원래 배열값에 음향을 주지 않음")

arr1 : [1 2 3 4 5]
arr2 : [100   2   3   4   5]
arr1 : [1 2 3 4 5] copy()메서드로 복사하면, 변경이 원래 배열값에 음향을 주지 않음


### 7.2.6. view와 copy
   - 파이썬 리스트와 넘파이의 ndarray의 차이 : 
        ndarray의 슬라이스는 배열의 복사본이 아닌, view라는 점
        view란, 원래 배열의 데이터를 가리키는 원본참조
        즉, ndarray의 슬라이스는 원본뎅터를 변경하게 된다.
        슬라이스를 복사본으로 만들려면 copy()메서드를 사용하여, arr[:].copy()로 사용한다.

In [0]:
# 7-17 : 아래 예제실행으로 파이썬의 리스트와 넘파이의 ndarray의 슬라이스의 차이를 확인한다.
import numpy as np

# 파이썬의 리스트에 넘파이를 대입한 경우를 살펴본다
arr_List = [x for x in range(10)]
print("리스트형 데이터입니다.")
print(arr_List)
print()

arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

print("리스트 슬라이스는 복사본이 생성되므로, arr_List에는 arr_List_copy의 변경이 반영되지 않습니다")
print("arr_List :", arr_List)
print("arr_List_copy :", arr_List_copy)

# NumPy의 ndarray의 슬라이스를 이용한 경우를 살펴봅니다.
arr_NumPy = np.arange(10);
print("NumPy의 ndarray데이터입니다.")
print("arr_NumPy :", arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

print("NumPy의 슬라이스는 View(데이터가 저장된 위치 정보)가 대입되므로, arr_NumPy_view의 정보를 변경하면, 원본인 arr_NumPy에도 반영된다.")
print("arr_NumPy_view :", arr_NumPy_view)
print("arr_NumPy :", arr_NumPy)
print()

# NumPy의 ndarray에서 copy를 사용한 경우를 살펴봅니다.
arr_NumPy = np.arange(10)
print("NumPy의 ndarray에서 copy를 사용한 경우를 살펴봅니다.")
print("arr_NumPy :", arr_NumPy)

arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

print("copy()를 사용하면 복사본이 생성되기 때문에 arr_NumPy_copy는 원본 arr_NumPy에 영향을 미치지 않는다.")
print("arr_NumPy :", arr_NumPy)


리스트형 데이터입니다.
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

리스트 슬라이스는 복사본이 생성되므로, arr_List에는 arr_List_copy의 변경이 반영되지 않습니다
arr_List : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr_List_copy : [100, 1, 2, 3, 4, 5, 6, 7, 8, 9]
NumPy의 ndarray데이터입니다.
arr_NumPy : [0 1 2 3 4 5 6 7 8 9]

NumPy의 슬라이스는 View(데이터가 저장된 위치 정보)가 대입되므로, arr_NumPy_view의 정보를 변경하면, 원본인 arr_NumPy에도 반영된다.
arr_NumPy_view : [100   1   2   3   4   5   6   7   8   9]
arr_NumPy : [100   1   2   3   4   5   6   7   8   9]

NumPy의 ndarray에서 copy를 사용한 경우를 살펴봅니다.
arr_NumPy : [0 1 2 3 4 5 6 7 8 9]
copy()를 사용하면 복사본이 생성되기 때문에 arr_NumPy_copy는 원본 arr_NumPy에 영향을 미치지 않는다.
arr_NumPy : [0 1 2 3 4 5 6 7 8 9]


### 7.2.7. 부울 인덱스 참조
   - 부울 인덱스 참조란, []안에 논리값(True/False값) 배열을 사용하여 요소를 추출하는 방법을 말한다.
   - arr[ndarray 논리값 배열] 로 표기하면 논리값(부울)배열의 True에 해당하는 배열의 요소의 ndarray를 만들어 반환해준다.

In [0]:
# 7-19 부울 인덱스 참조의 예
import numpy as np
arr = np.array([2,4,6,7])
print(arr[np.array([True, True, True, False])])

[2 4 6]


In [0]:
# 7-20 부울 인덱스 참조의 예
import numpy as np
arr = np.array([2,4,6,7])
print(arr[arr%3 == True]) # True == 1, 나머지가 1인것을 참으로 하여, 

[4 7]


In [0]:
# 7-21
import numpy as np

arr = np.array([2,3,4,5,6,7])
# 변수 arr 의 각 요소가 2로 나누어 떨어지는지 나타내는 부울 배열을 출력하세요
print(arr)
print(arr%2 == 0)       # print(조건) 은 ndarray가 조건에 대해 참True인지 거짓False인지 출력해주고
print(arr[arr%2 == False])  # print(arr[인덱스에 대한 조건]) 은 조건이 참인 요소만 출력한다.

[2 3 4 5 6 7]
[ True False  True False  True False]
[2 4 6]


### 7.2.8. 범용 함수 universal function
   - 범용함수 : ndarray 배열의 각 요소에 대한 연산 결과를 반환하는 함수
   - 요소별로 계산하므로 다차원 배열에도 사용가능
   - 범용함수는 인수가 하나인 경우와 두 개인 경우가 있다
   - 인수가 하나인 경우 : 요소의 절댓값을 반환하는 np.abs()함수,요소의 exp반환하는 np.exp(), 요소의 제곱근을 반환하는 np.sqrt() 등이 있음
   - 인수가 두 개인 경우 : 요소간의 합을 반환하는 np.add(), 요소간의 차를 반환하는 np.subtract(), 요소간의 최대값을 저장한 배열을 반환하는 np.maximum()

In [0]:
# 7-23
import numpy as np
arr = np.array([4,-9,16,-4,20])
print(arr)

# 변수 arr의 각 요소를 절댓값으로 하여, 변수 arr_abs에 대입하세요.
arr_abs = np.abs(arr)
print(arr_abs)

# 변수 arr_abs의 각 요소의 e의 거듭제곱근과 제곱근을 출력하세요
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


### 7.2.9. 집합 함수
   - 집합 함수란  수학의 집합 연산을 수행하는 함수 (1차원 배열만을 대상으로 한다)
   - 대표적인 집합 함수로는 배열 요소에서 중복을 제거하고 정렬한 결과를 반환하는 np.unique()
   - 배열x와 y의 합집합을 정렬해서 반환하는 np.union1d(x, y) 함수
   - 배열 x와 y의 교집합을 정렬해서 반환하는 np.intersect1d(x,y)함수
   - 배열 x에서 배열 y를 뺀 차집합을 정렬해서 반환하는 np.setdiff1d(x,y)함수

In [0]:
# 7-25
import numpy as np

arr1 = [2,5,7,9,5,2]
arr2 = [2,5,8,3,1]

# np.unique()함수를 사용하여 변수 arr1에서 중복을 제거한 배열을 변수 new_arr1에 대입
new_arr1 = np.unique(arr1)
print(new_arr1)

# 변수 new_arr1과 변수 arr2의 합집합을 출력하세요
print(np.union1d(new_arr1, arr2))

# 변수 new_arr1과 arr2의 교집합
print(np.intersect1d(new_arr1,arr2))

# 변수 new_arr1에서 변수 arr2를 뺀 차집합
print(np.setdiff1d(new_arr1,arr2))

[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


### 7.2.10. 난수
   - NumPy는 np.random 모듈로 난수(정의된 범위 내에서 무작위로 추출된 수)를 생성할 수 있다
   - np.random() 은 0이상, 1미만의 난수를 생성하는 np.random.rand()함수
   - x이상, y미만의 정수를 z개 생성하는 np.random.randint(x,y,z)함수
   - 가우스 분포를 따르는 난수를 생성하는 np.random.normal()함수가 있다.
   - np.random.rand()함수는 ()안에 넣은 정수의 횟수만큼 난수가 생성된다.
   - np.random.randint(x,y,z)함수는 x이상, y미만의 정수를 생성하는 점에 주의
   - z에는 (2, 3)등의 인수를 넣을 수도 있어, 2x3행렬을 쉽게 생성 가능
   - 일반적으로는 np.random.randint() 로 난수를 생성하는 경우가 많음
   - 매번 사용하는 np.random.randint()와 같이 np.random을 반복하지 않기 위해
   - from numpy.random import randint 기술해 두면, randint만으로 함수를 사용가능
   - from 모듈명 import 모듈내 함수명

In [0]:
# 7-27
import numpy as np
from numpy.random import randint
arr1 = randint(0,10,(5,2))
print(arr1)
arr2 = np.random.rand(3)
print(arr2)

[[0 7]
 [3 4]
 [7 1]
 [1 2]
 [1 1]]
[0.75168608 0.20446933 0.93673687]


## 7.3. NumPy 2차원 배열
### 7.3.1. 2차원 배열
   - 1차원 배열에서 언급하였듯이 2차원 배열은 행렬. np.arry([list,list])로 2차원 배열생성
   - ndarray배열의 내부에는 shape라는 변수가 있어, ndarray배열.shape로 각 차원의 요소수를 반환할 수 있음
   - ndarray배열.reshape(a,b)로 지정한 인수와 같은 모양의 행렬로 변환
   - ndarray변수를 넣지 않고 ndarray배열 자체를 넣어도 마찬가지로 반환

In [0]:
# 7-29
import numpy as np

# 변수 arr에 2차원 배열을 대입
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

# 변수 arr행렬의 각 차원의 요소 수를 출력
print(np.shape(arr))

# 변수 arr을 4행 2열의 행렬로 변환
print(arr.reshape(4,2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 7.3.2. 인덱스 참조와 슬라이스
   - 2차원 배열의 경우, 인덱스를 하나만 지정하면, 임의의 행을 배열로 가져올 수 있다.
   - 개별 요소, 즉 스칼라값에 도달하려면, 인덱스를 두 개 지정해야 한다.
   - arr[1][2] 또는 arr[1,2]와 같이 접근할 필요가 있음.
   - arr[1][2]는 arr[1]에서 꺼낸 배열의 세 번째 요소에 접근하고, arr[1,2]는 2차원 배열의 축을 지정하여 요소에 접근하게 됨

In [0]:
# 7-31 : 인덱스 참조의 예
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1])

[[1 2 3]
 [4 5 6]]
[4 5 6]


In [0]:
# 7-32 : 인덱스 참조의 예 2
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

6


In [0]:
# 2차원 배열 참조 시, 슬라이스를 사용할 수 있다.
# 7-33 : 슬라이스의 예
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,1:])

[5 6]


In [0]:
# 7-34
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

# 변수 arr의 요소 중 3을 출력하세요
print(arr[0,2])
# 변수 arr에서 부분적으로 요소를 추출해서 출력하세요
print(arr[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


### 7.3.3. axis (좌표축)
   - NumPy 함수의 인수로 axis를 설정하는 경우가 많음.
   - 열마다 처리하는 축이 axis=0, 행마다 처리하는 축이 axis=1
   - ndarray배열의 sum()메서드인 경우, ndarray.sum)을 요소를 모두 더할수있음

In [0]:
# 7-36 : axis의 예
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(1+2+3+4+5+6)
print(arr.sum())    # sum()메서드에 인수를 지정하지 않으면, 단순합계가 스칼라 반환됨
print(arr.sum(axis=0)) # sum()메서드에 axis=0을 지정하면 세로로 더해진다. 행
print(arr.sum(axis=1)) # sum()메서드에 axis=1을 지정하면 가로로 더해진다.열

[[1 2 3]
 [4 5 6]]
21
21
[5 7 9]
[ 6 15]


In [0]:
# 7-37
import numpy as np

arr = np.array([[1,2,3],[4,5,12],[15,20,22]])
print(arr)

# arr행의 합을 구하여 문제에서 제시한 1차원 배열을 반환
print(arr.sum(axis=1))

[[ 1  2  3]
 [ 4  5 12]
 [15 20 22]]
[ 6 21 57]


### 7.3.4. 팬시 인덱스 참조
   - 팬시 인덱스 참조는 인덱스 참조로 인덱스의 배열을 이용하는 방법이다.
   - ndarray배열에서 특정 순서로 행을 추출하려면, 그 순서를 나타내는 배열을 인덱스 참조로 전달한다.
   - 팬시 인덱스 참조는 슬라이스와는 달리, 항상 원본 데이터의 복사본을 반환하여 새로운 요소를 작성한다.

In [0]:
# 7-39 : 팬시 인덱스 참조의 예
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr)

# 3행, 2행, 0행을 순서대로 추출하여 새로운 요소를 만든다.
# 인덱스 번호는 0부터 시작한다.
print(arr[[3,2,0]])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[7 8]
 [5 6]
 [1 2]]


In [0]:
# 7-40 :
import numpy as np
arr = np.arange(25).reshape(5,5)
print(arr)
# 변수 arr의 행의 순서를 변경하여 출력
print(arr[[1,3,0]],"\n")
print(arr[[2]])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]] 

[[10 11 12 13 14]]


### 7.3.5. 전치 행렬
   - 행렬에서 행과 열을 바꾸는 것 : 전치 transposed matrix는 행렬내적계산에 사용됨
   - ndarray를 전치하려면, np.transpose()함수를 사용하거나 T를 사용한다.

In [0]:
# 7-42
import numpy as np

arr = np.arange(10).reshape(2,5)
print(arr,"\n")
print(np.transpose(arr),"\n")
print(arr.T)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] 

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 7.3.6. 정렬
   - ndarray도 리스트형과 마찬가지로 sort()메서드로 정렬할 수 있다.
   - 2차원 배열의 경우 0을 인수로 하면, 열단위로 요소가 정렬되며,
   - 1을 인수로 하면 행 단위로 요소가 정렬된다.
   - 또한, np.sort() 함수로도 정렬할 수 있다. sort()메서드와 달리, np.sort()함수는 정렬된 배열의 복사본을 반환한다.
   - ML에 자주 사용되는 함수로 argsort() 메서드가 있는데, 
   - argsort()메서드는 정렬된 배열의 인덱스를 반환한다.

In [0]:
# 7-44 정렬의 예
import numpy as np
arr = np.array([15,30,5])
arr.argsort()

array([2, 0, 1])

In [0]:
# 7-45
import numpy as np

arr = np.array([[8,4,2],[3,5,1]])
print(arr)
# argsort()메서드로 정렬하여 출력
# argsort()메서드는 정렬된 배열의 인덱스를 반환
print(arr.argsort())

# np.sort()함수로 정렬하여 출력
print(np.sort(arr))

# sort()메서드로 행을 정렬하여 출력 : 행정렬1, 열정렬0
print(arr.sort(1))
print(arr)

[[8 4 2]
 [3 5 1]]
[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
None
[[2 4 8]
 [1 3 5]]


### 7.3.7. 행렬 계산
   - 두 행렬의 행렬곱을 반환하는 np.dot(a,b)와 노름을 반환하는 np.linalg.norm(a)
   - 행렬곱 : 행렬에서 행백터와 열벡터의 내적을 요소로 하는 행렬
             np.dot(a,b)함수를 실행하면 행벡터 a와 열벡터 b의 행렬곱이 생성됨
   - 노름 : 벡터의 길이를 반환하는 것. 요소의 제곱값을 더해 루트를 씌운 것
             np.linalg.norm(a) 함수 실행시 벡터 a와 b의 노름이 출력된다.

In [3]:
# 7-48 
import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)
# arr x arr
print("\narr x arr : \n", np.dot(arr,arr))
# vec redefine
vec = arr.reshape(9)
print(vec)
# norm
print("\nnorm\n", np.linalg.norm(vec))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

arr x arr : 
 [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[0 1 2 3 4 5 6 7 8]

norm
 14.2828568570857


### 7.3.8. 통계 함수
mean()
np.average()
sum()
np.max() np.min()
np.argmax() np.argmin()
np.std() np.var()
인수 axis=0 열, axis=1 행

In [4]:
# 7-49
import numpy as np
arr = np.arange(15).reshape(3,5)
# 변수 arr의 각 열의 평균
print(arr.mean(axis=0))
# 변수 arr의 각 행 합계
print(arr.sum(axis=1))
# 변수 arr의 최소값
print(np.min(arr))
# 변수 arr의 각 열의 최대값의 인덱스
print(arr.argmax(axis=0))

[5. 6. 7. 8. 9.]
[10 35 60]
0
[2 2 2 2 2]


### 7.3.9 브로드캐스트

In [5]:
# 7-51 브로드캐스트의 예
import numpy as np
x = np.arange(6).reshape(2,3)
print(x+1)

[[1 2 3]
 [4 5 6]]


In [10]:
# 7-52
import numpy as np

x = np.arange(15).reshape(3,5)
y = np.array([np.arange(5)])
print("x :\n",x)
print("y :\n",y)
z = x-y
print("\nz :\n",z)
print("행렬의 크기는 맞았지만, 요소가 없으므로 0으로 채워짐")

x :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
y :
 [[0 1 2 3 4]]

z :
 [[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
행렬의 크기는 맞았지만, 요소가 없으므로 0으로 채워짐


In [16]:
# 7-54
import numpy as np

np.random.seed(100)

# 각 요소가 0~30인 정수행렬 5x3을 변수 arr에 대입하세요
arr = np.random.randint(0,31,(5,3))
print("arr :\n", arr)
# 변수 arr를 전치하세요
arr = arr.T
print("arr transposed :\n",arr)
# 변수 arr의 2,3,4열만 추출한 행렬(3x3)을 변수 arr1에 대입하세요
arr1 = arr[:,1:4]
print("arr1 :\n", arr1)
# 변수 arr1의 행을 정렬하세요
arr1.sort(0)
print(arr1)
# 각 열의 평균을 출력하세요
arr1.mean(axis=0)
print(arr1)
print(arr1.mean(axis=0))

arr :
 [[ 8 24  3]
 [ 7 23 15]
 [16 10 30]
 [20  2 21]
 [ 2  2 14]]
arr transposed :
 [[ 8  7 16 20  2]
 [24 23 10  2  2]
 [ 3 15 30 21 14]]
arr1 :
 [[ 7 16 20]
 [23 10  2]
 [15 30 21]]
[[ 7 10  2]
 [15 16 20]
 [23 30 21]]
[[ 7 10  2]
 [15 16 20]
 [23 30 21]]
[15.         18.66666667 14.33333333]


In [18]:
# 7-56
import numpy as np

#난수를 초기화
np.random.seed(0)

# 가로세로 크기를 전달하면 해당 크기의 이미지를 난수로 채워서 생성하는 함수
def make_image(m,n):
  # n x m, each element = 0~5 random value
  image = np.random.randint(0,6,(m,n))
  return image

# 전달된 행렬의 일부를 변경하는 함수
def change_little(matrix):
  # 전달받은 행렬의 형태(크기) 를 취득하여 shape에 대입
  shape = matrix.shape
  # 행렬의 각 성분에 대해 변경 여부를 무작위로 결정한 다음
  # 변경할 때는 0~5 사이의 정수로 임의 교체하세요
  for i in range(shape[0]):
    for j in range(shape[1]):
      if np.random.randint(0,2)==1:
        matrix[i][j] = np.random.randint(0,6,1)
        
  return matrix

# 임의의 이미지를 만듭니다.
image1 = make_image(3,3)
print(image1)
print()
# 임의의 변경사항을 적용합니다.
image2 = change_little(np.copy(image1))
print(image2)
print()
# image1, image2의 차이를 계산하여 image3에 대입하세요.
image3 = image1 - image2
print(image3)
print()
# image3의 각 성분을 절댓값으로 한 행렬을 image3에 다시 대입하세요.
image3 = np.abs(image3)
# image3을 출력합니다.
print(image3)


[[4 5 0]
 [3 3 3]
 [1 3 5]]

[[4 5 0]
 [3 3 3]
 [0 5 5]]

[[ 0  0  0]
 [ 0  0  0]
 [ 1 -2  0]]

[[0 0 0]
 [0 0 0]
 [1 2 0]]
